steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: ["pull", "gcr.io/golden-agency-161021/github-brndnmtthws-my-crappy-website:latest"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/golden-agency-161021/github-brndnmtthws-my-crappy-website:$REVISION_ID", "-t", "gcr.io/golden-agency-161021/github-brndnmtthws-my-crappy-website:latest", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/golden-agency-161021/github-brndnmtthws-my-crappy-website:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/golden-agency-161021/github-brndnmtthws-my-crappy-website:latest"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - my-crappy-website
  - my-crappy-website=gcr.io/golden-agency-161021/github-brndnmtthws-my-crappy-website:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
